library(tidyverse)
###data imported manually
#wrangling
ari <- arizonadiamondbacks %>% select(Opp, R, RA) %>% mutate(rdiff = R-RA) %>% select(Opp, rdiff)
atl <- atlantabraves %>% select(Opp, R, RA) %>% mutate(rdiff = R-RA) %>% select(Opp, rdiff)
bal <- baltimoreorioles %>% select(Opp, R, RA) %>% mutate(rdiff = R-RA) %>% select(Opp, rdiff)
bos <- bostonredsox %>% select(Opp, R, RA) %>% mutate(rdiff = R-RA) %>% select(Opp, rdiff)
chc <- chicagocubs %>% select(Opp, R, RA) %>% mutate(rdiff = R-RA) %>% select(Opp, rdiff)
chw <- chicagowhitesox %>% select(Opp, R, RA) %>% mutate(rdiff = R-RA) %>% select(Opp, rdiff)
cin <- cincinnatireds %>% select(Opp, R, RA) %>% mutate(rdiff = R-RA) %>% select(Opp, rdiff)
cle <- clevelandindians %>% select(Opp, R, RA) %>% mutate(rdiff = R-RA) %>% select(Opp, rdiff)
col <- coloradorockies %>% select(Opp, R, RA) %>% mutate(rdiff = R-RA) %>% select(Opp, rdiff)
det <- detroittigers %>% select(Opp, R, RA) %>% mutate(rdiff = R-RA) %>% select(Opp, rdiff)
hou <- houstonastros %>% select(Opp, R, RA) %>% mutate(rdiff = R-RA) %>% select(Opp, rdiff)
kcr <- kansascityroyals %>% select(Opp, R, RA) %>% mutate(rdiff = R-RA) %>% select(Opp, rdiff)
laa <- laangels %>% select(Opp, R, RA) %>% mutate(rdiff = R-RA) %>% select(Opp, rdiff)
lad <- ladodgers %>% select(Opp, R, RA) %>% mutate(rdiff = R-RA) %>% select(Opp, rdiff)
mia <- miamimarlins %>% select(Opp, R, RA) %>% mutate(rdiff = R-RA) %>% select(Opp, rdiff)
mil <- milwaukeebrewers %>% select(Opp, R, RA) %>% mutate(rdiff = R-RA) %>% select(Opp, rdiff)
min <- minnesotatwins %>% select(Opp, R, RA) %>% mutate(rdiff = R-RA) %>% select(Opp, rdiff)
nym <- nymets %>% select(Opp, R, RA) %>% mutate(rdiff = R-RA) %>% select(Opp, rdiff)
nyy <- nyyankees %>% select(Opp, R, RA) %>% mutate(rdiff = R-RA) %>% select(Opp, rdiff)
oak <- oaklandas %>% select(Opp, R, RA) %>% mutate(rdiff = R-RA) %>% select(Opp, rdiff)
phi <- philadelphiaphillies %>% select(Opp, R, RA) %>% mutate(rdiff = R-RA) %>% select(Opp, rdiff)
pit <- pittsburghpirates %>% select(Opp, R, RA) %>% mutate(rdiff = R-RA) %>% select(Opp, rdiff)
sdp <- sandiegopadres %>% select(Opp, R, RA) %>% mutate(rdiff = R-RA) %>% select(Opp, rdiff)
sfg <- sanfranciscogiants %>% select(Opp, R, RA) %>% mutate(rdiff = R-RA) %>% select(Opp, rdiff)
sea <- seattlemariners %>% select(Opp, R, RA) %>% mutate(rdiff = R-RA) %>% select(Opp, rdiff)
stl <- stlouiscardinals %>% select(Opp, R, RA) %>% mutate(rdiff = R-RA) %>% select(Opp, rdiff)
tbr <- tampabayrays %>% select(Opp, R, RA) %>% mutate(rdiff = R-RA) %>% select(Opp, rdiff)
tex <- texasrangers %>% select(Opp, R, RA) %>% mutate(rdiff = R-RA) %>% select(Opp, rdiff)
tor <- torontobluejays %>% select(Opp, R, RA) %>% mutate(rdiff = R-RA) %>% select(Opp, rdiff)
wsn <- washingtonnationals %>% select(Opp, R, RA) %>% mutate(rdiff = R-RA) %>% select(Opp, rdiff)


library(RMySQL)
con <- dbConnect(MySQL(),
                 user = 'blakeobeans',
                 password = 'MrJ0nes123',
                 host = 'mydbinstance4.c1uducbod6js.us-west-1.rds.amazonaws.com',
                 dbname='blakeobeans')

###uploading baseball data
dbWriteTable(conn = con, name = 'ari', value = ari, overwrite = TRUE) 
dbWriteTable(conn = con, name = 'atl', value = atl, overwrite = TRUE)
dbWriteTable(conn = con, name = 'bal', value = bal, overwrite = TRUE)
dbWriteTable(conn = con, name = 'bos', value = bos, overwrite = TRUE)
dbWriteTable(conn = con, name = 'chc', value = chc, overwrite = TRUE)
dbWriteTable(conn = con, name = 'chw', value = chw, overwrite = TRUE)
dbWriteTable(conn = con, name = 'cin', value = cin, overwrite = TRUE)
dbWriteTable(conn = con, name = 'cle', value = cle, overwrite = TRUE)
dbWriteTable(conn = con, name = 'col', value = col, overwrite = TRUE) 
dbWriteTable(conn = con, name = 'det', value = det, overwrite = TRUE)
dbWriteTable(conn = con, name = 'hou', value = hou, overwrite = TRUE)
dbWriteTable(conn = con, name = 'kcr', value = kcr, overwrite = TRUE)
dbWriteTable(conn = con, name = 'laa', value = laa, overwrite = TRUE)
dbWriteTable(conn = con, name = 'lad', value = lad, overwrite = TRUE)
dbWriteTable(conn = con, name = 'mia', value = mia, overwrite = TRUE)
dbWriteTable(conn = con, name = 'mil', value = mil, overwrite = TRUE)
dbWriteTable(conn = con, name = 'min', value = min, overwrite = TRUE) 
dbWriteTable(conn = con, name = 'nym', value = nym, overwrite = TRUE)
dbWriteTable(conn = con, name = 'nyy', value = nyy, overwrite = TRUE)
dbWriteTable(conn = con, name = 'oak', value = oak, overwrite = TRUE)
dbWriteTable(conn = con, name = 'phi', value = phi, overwrite = TRUE)
dbWriteTable(conn = con, name = 'pit', value = pit, overwrite = TRUE)
dbWriteTable(conn = con, name = 'sdp', value = sdp, overwrite = TRUE)
dbWriteTable(conn = con, name = 'sfg', value = sfg, overwrite = TRUE)
dbWriteTable(conn = con, name = 'sea', value = sea, overwrite = TRUE) 
dbWriteTable(conn = con, name = 'stl', value = stl, overwrite = TRUE)
dbWriteTable(conn = con, name = 'tbr', value = tbr, overwrite = TRUE)
dbWriteTable(conn = con, name = 'tex', value = tex, overwrite = TRUE)
dbWriteTable(conn = con, name = 'tor', value = tor, overwrite = TRUE)
dbWriteTable(conn = con, name = 'wsn', value = wsn, overwrite = TRUE)
